default.rails_install.app_name = "some_app"
# default.rails_install.db_pass = "secret"
default.rails_install.repository = "https://github.com/averell23/badgeworld.git"
default.rails_install.server_name = "badges.furrycreatures.net"
# default.mysql.server_root_password = "fnordfnordfnordfnord"
# default.mysql.server_debian_password = "fnordfnordfnordfnord"
# default.mysql.server_repl_password = "fnordfnordfnordfnord"
